name: Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest # Use bash shell with 256color support
    env:
      TERM: xterm-256color
    steps:
      - name: Run command
        run: echo $TERM
